[project]
name = "stax"
version = "0.1.0"
description = "A JAX deep learning stack"
readme = "README.md"
authors = [
    { name = "adityamakkar000", email = "aditymakkar000@gmail.com" },
    { name = "jindal013", email = "chinmayjindal108@gmail.com" },
    { name = "divyamakkar0", email="divyamakkar000@gmail.com"}
]

requires-python = ">=3.12"

dependencies = [
    "etils[epath]>=1.14.0",
    "flax>=0.11.0",
    "jax>=0.8.0",
    "jaxtyping",
    "loguru>=0.7.3",
    "orbax-checkpoint>=0.11.36",
    "pre-commit>=4.5.1",
    "ruff>=0.14.10",
    "tensorboard>=2.20.0",
    "tensorboard-plugin-profile>=2.21.3",
    "tensorflow>=2.21.0",
    "wandb>=0.22.3",
]

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

