from loguru import logger

from stax.utils import get_rank


class FakeLogger:
    def debug(self, msg, *args, **kwargs): ...
    def info(self, msg, *args, **kwargs): ...
    def warning(self, msg, *args, **kwargs): ...
    def error(self, msg, *args, **kwargs): ...
    def critical(self, msg, *args, **kwargs): ...


staxLogger = logger if (get_rank() == 0) else FakeLogger()

__all__ = ["staxLogger"]
